from pathlib import Path

from aind_behavior_services.session import AindBehaviorSessionModel
from contraqctor.contract import Dataset, DataStreamCollection
from contraqctor.contract.harp import (
    DeviceYmlByFile,
    HarpDevice,
)
from contraqctor.contract.json import PydanticModel, SoftwareEvents
from contraqctor.contract.text import Text

from ..rig import OlfactometerCalibrationRig
from ..task_logic import OlfactometerCalibrationLogic


def dataset(
    root_path: Path,
    name: str = "OlfactometerCalibrationDataset",
    description: str = "A Olfactometer Calibration dataset",
    version: str = "0.3.0",
) -> Dataset:
    """
    Creates a Dataset object for the Olfactometer calibration procedure.
    """

    root_path = Path(root_path)
    return Dataset(
        name=name,
        version=version,
        description=description,
        data_streams=[
            DataStreamCollection(
                name="Behavior",
                description="Data from the Behavior modality",
                data_streams=[
                    HarpDevice(
                        name="HarpOlfactometer",
                        reader_params=HarpDevice.make_params(
                            path=root_path / "behavior/Olfactometer.harp",
                            device_yml_hint=DeviceYmlByFile(),
                        ),
                    ),
                    HarpDevice(
                        name="HarpClockGenerator",
                        reader_params=HarpDevice.make_params(
                            path=root_path / "behavior/WhiteRabbit.harp",
                            device_yml_hint=DeviceYmlByFile(),
                        ),
                    ),
                    HarpDevice(
                        name="HarpAnalogInput",
                        reader_params=HarpDevice.make_params(
                            path=root_path / "behavior/AnalogInput.harp",
                            device_yml_hint=DeviceYmlByFile(),
                        ),
                    ),
                    DataStreamCollection(
                        name="HarpCommands",
                        description="Commands sent to Harp devices",
                        data_streams=[
                            HarpDevice(
                                name="HarpOlfactometer",
                                reader_params=HarpDevice.make_params(
                                    path=root_path / "behavior/HarpCommands/Olfactometer.harp",
                                    device_yml_hint=DeviceYmlByFile(),
                                ),
                            ),
                            HarpDevice(
                                name="HarpClockGenerator",
                                reader_params=HarpDevice.make_params(
                                    path=root_path / "behavior/HarpCommands/WhiteRabbit.harp",
                                    device_yml_hint=DeviceYmlByFile(),
                                ),
                            ),
                            HarpDevice(
                                name="HarpAnalogInput",
                                reader_params=HarpDevice.make_params(
                                    path=root_path / "behavior/HarpCommands/AnalogInput.harp",
                                    device_yml_hint=DeviceYmlByFile(),
                                ),
                            ),
                        ],
                    ),
                    DataStreamCollection(
                        name="SoftwareEvents",
                        description="Software events generated by the workflow. The timestamps of these events are low precision and should not be used to align to physiology data.",
                        data_streams=[
                            SoftwareEvents(
                                name="OdorChannel",
                                description="The OdorChannel currently being used.",
                                reader_params=SoftwareEvents.make_params(
                                    root_path / "behavior/SoftwareEvents/OdorChannel.json"
                                ),
                            ),
                            SoftwareEvents(
                                name="IsEndValveCalibration",
                                description="Whether the calibration is running in end-valve mode or not.",
                                reader_params=SoftwareEvents.make_params(
                                    root_path / "behavior/SoftwareEvents/IsEndValveCalibration.json"
                                ),
                            ),
                        ],
                    ),
                    DataStreamCollection(
                        name="Logs",
                        data_streams=[
                            Text(
                                name="Launcher",
                                description="Contains the console log of the launcher process.",
                                reader_params=Text.make_params(
                                    path=root_path / "behavior/Logs/.launcher/launcher.log",
                                ),
                            ),
                            SoftwareEvents(
                                name="EndSession",
                                description="A file that determines the end of the session. If the file is empty, the session is still running or it was not closed properly.",
                                reader_params=SoftwareEvents.make_params(
                                    path=root_path / "behavior/Logs/EndSession.json",
                                ),
                            ),
                        ],
                    ),
                    DataStreamCollection(
                        name="InputSchemas",
                        description="Configuration files for the behavior rig, task_logic and session.",
                        data_streams=[
                            PydanticModel(
                                name="Rig",
                                reader_params=PydanticModel.make_params(
                                    model=OlfactometerCalibrationRig,
                                    path=root_path / "behavior/Logs/rig_input.json",
                                ),
                            ),
                            PydanticModel(
                                name="TaskLogic",
                                reader_params=PydanticModel.make_params(
                                    model=OlfactometerCalibrationLogic,
                                    path=root_path / "behavior/Logs/tasklogic_input.json",
                                ),
                            ),
                            PydanticModel(
                                name="Session",
                                reader_params=PydanticModel.make_params(
                                    model=AindBehaviorSessionModel,
                                    path=root_path / "behavior/Logs/session_input.json",
                                ),
                            ),
                        ],
                    ),
                ],
            ),
        ],
    )
